[Values]
# Set to true to use the next variable as default when asked what version the file is
AutoSetVersion=False
# What version the ITS file is from, for use with AutoSetVersion
Version=P
# Whether to include Pots and Horses in the output
IncludePotsAndHorses=True
PrintItemID=True
PrintSize=True
PrintRot=True
PrintCoords=True